#!/usr/bin/env python3
"""Generate figures/tbl-timing.tex and data/timing-macros.tex from the
interleaved measurement in /private/tmp/cpp-timing/timings.csv.

Reports the mean over all complete rounds and, separately, the mean with the
cold first round dropped, since the first build of a session is consistently
slower on this machine."""
import csv, statistics, sys, collections

SRC = "/private/tmp/cpp-timing/timings.csv"
NAME = {"A-paco": r"\cpaco{}", "B-oldport": r"\cold{}", "C-newport": r"\cnew{}"}
ORDER = ["A-paco", "B-oldport", "C-newport"]

rows = [r for r in csv.DictReader(open(SRC)) if r["seconds"] != "FAILED"]
by = collections.defaultdict(dict)
for r in rows:
    by[int(r["round"])][r["checkpoint"]] = float(r["seconds"])
complete = sorted(k for k, v in by.items() if len(v) == 3)
if not complete:
    sys.exit("no complete rounds yet")
warm = [k for k in complete if k != min(complete)]

def mean(cp, rounds):
    return statistics.mean(by[k][cp] for k in rounds)

base_all, base_warm = mean("A-paco", complete), mean("A-paco", warm or complete)

lines = [
 "%% GENERATED by paper/gen-timing.py -- do not edit by hand.",
 r"\begin{table}[t]",
 r"\caption{Wall-clock time for a full serial build of Interaction Trees at each",
 r"checkpoint, in seconds. Builds are interleaved rather than blocked, and the",
 f"coinduction library is prebuilt, so the timed region is the Interaction Trees",
 f"development itself. Mean over {len(complete)} rounds, and over the"
 f" {len(warm)} rounds after the cold first one.}}",
 r"\label{tab:timing}", r"\centering", r"\small",
 r"\begin{tabular}{@{}lrrrr@{}}", r"\toprule",
 r"Checkpoint & \multicolumn{2}{c}{All rounds} & \multicolumn{2}{c}{Warm rounds} \\",
 r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}",
 r" & mean & vs.\ \paco{} & mean & vs.\ \paco{} \\", r"\midrule",
]
for cp in ORDER:
    a, w = mean(cp, complete), mean(cp, warm or complete)
    da = "---" if cp == "A-paco" else f"${100*(a-base_all)/base_all:+.1f}\\%$"
    dw = "---" if cp == "A-paco" else f"${100*(w-base_warm)/base_warm:+.1f}\\%$"
    lines.append(f"{NAME[cp]} & {a:.1f} & {da} & {w:.1f} & {dw} \\\\")
lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
open("figures/tbl-timing.tex", "w").write("\n".join(lines) + "\n")

old = mean("B-oldport", warm or complete); new = mean("C-newport", warm or complete)
m = [
 "%% GENERATED by paper/gen-timing.py -- do not edit by hand.",
 f"\\newcommand{{\\oldSlowPct}}{{{100*(old-base_warm)/base_warm:.0f}\\%}}",
 f"\\newcommand{{\\newSlowPct}}{{{100*(new-base_warm)/base_warm:.1f}\\%}}",
 f"\\newcommand{{\\timingRounds}}{{{len(complete)}}}",
]
open("data/timing-macros.tex", "w").write("\n".join(m) + "\n")
print("\n".join(m))
print(f"rounds complete: {complete}; warm: {warm}")
